#ifndef HERDR_CORE_H
#define HERDR_CORE_H

/* Generated by cbindgen. Do not modify; regenerate via scripts/build-herdr-core.sh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define HERDR_CODE_OK 0

#define HERDR_CODE_INVALID_ARGUMENT 1

#define HERDR_CODE_PANIC 2

#define HERDR_CODE_DISCONNECTED 3

#define HERDR_CODE_PROTOCOL_VIOLATION 4

#define HERDR_CODE_HANDSHAKE_TIMED_OUT 5

#define HERDR_CODE_HANDSHAKE_EXPECTED_WELCOME 6

#define HERDR_CODE_HANDSHAKE_INVALID_WELCOME 7

#define HERDR_CODE_HANDSHAKE_INCOMPATIBLE 8

#define HERDR_CODE_HANDSHAKE_REJECTED 9

#define HERDR_CODE_NOT_ONLINE 10

#define HERDR_CODE_INPUT_FROZEN 11

#define HERDR_CODE_INPUT_STALE_TARGET 12

#define HERDR_CODE_INPUT_WRITE_FAILED 13

#define HERDR_CODE_SURFACE_REJECTED 14

#define HERDR_CODE_CLIENT_FAILED 15

#define HERDR_INPUT_TEXT_COMMIT 0

#define HERDR_INPUT_KEY 1

#define HERDR_INPUT_PASTE 2

#define HERDR_KEY_BACKSPACE 1

#define HERDR_KEY_ENTER 2

#define HERDR_KEY_LEFT 3

#define HERDR_KEY_RIGHT 4

#define HERDR_KEY_UP 5

#define HERDR_KEY_DOWN 6

#define HERDR_KEY_HOME 7

#define HERDR_KEY_END 8

#define HERDR_KEY_PAGE_UP 9

#define HERDR_KEY_PAGE_DOWN 10

#define HERDR_KEY_TAB 11

#define HERDR_KEY_BACK_TAB 12

#define HERDR_KEY_DELETE 13

#define HERDR_KEY_INSERT 14

#define HERDR_KEY_ESC 15

#define HERDR_KEY_CHAR 16

#define HERDR_KEY_FUNCTION 17

#define HERDR_KEY_NULL 18

#define HERDR_KEY_KIND_PRESS 0

#define HERDR_KEY_KIND_REPEAT 1

#define HERDR_KEY_KIND_RELEASE 2

#define HERDR_PHASE_AWAITING_WELCOME 0

#define HERDR_PHASE_ONLINE 1

#define HERDR_PHASE_FAILED 2

/**
 * Opaque client handle; the pointed-to allocation is owned by the caller and
 * released only through `herdr_client_destroy`. The C side never dereferences
 * it — every ABI call casts back to the Rust payload internally.
 */
typedef struct herdr_client {
  uint8_t _private[0];
} herdr_client;

/**
 * Integer widths and nullable rules are explicit per field; all strings are
 * UTF-8 and NUL-terminated unless a length is provided instead.
 */
typedef struct herdr_client_config {
  /**
   * Logical surface columns; must be 1..=u16::MAX.
   */
  uint32_t cols;
  /**
   * Logical surface rows; must be 1..=u16::MAX.
   */
  uint32_t rows;
  /**
   * Cell width in physical pixels (0 when unknown).
   */
  uint32_t cell_width_px;
  /**
   * Cell height in physical pixels (0 when unknown).
   */
  uint32_t cell_height_px;
  /**
   * Advertise SGR pixel-mouse support only with exact geometry (doc §7).
   */
  bool pixel_mouse;
  /**
   * Advertise shell mouse capture only when pointer capture is implemented.
   */
  bool mouse_capture;
  /**
   * Inbound frame-size ceiling; 0 selects the protocol default.
   */
  uint32_t max_frame_size;
  /**
   * Outbound queue message budget; 0 selects the default (256).
   */
  uint32_t outbound_message_limit;
  /**
   * Outbound queue byte budget; 0 selects the default (4 MiB).
   */
  uint32_t outbound_byte_limit;
} herdr_client_config;

/**
 * Structured call result; `detail` is a borrowed, NUL-terminated UTF-8
 * diagnostic (null when code == HERDR_CODE_OK).
 */
typedef struct HerdrResult {
  int32_t code;
  const char *detail;
} HerdrResult;

typedef struct herdr_key {
  /**
   * HERDR_KEY_* constant; CHAR and FUNCTION read `codepoint`.
   */
  uint32_t code;
  /**
   * Unicode scalar (CHAR) or function-key number 1..=35 (FUNCTION).
   */
  uint32_t codepoint;
  /**
   * Crossterm-compatible modifier bits.
   */
  uint8_t modifiers;
  /**
   * HERDR_KEY_KIND_PRESS/REPEAT/RELEASE.
   */
  uint8_t kind;
  uint16_t repeat_count;
  /**
   * Shifted unicode scalar; 0 when unavailable.
   */
  uint32_t shifted_codepoint;
} herdr_key;

/**
 * One semantic pane input event, routed to an explicit pane identity.
 */
typedef struct herdr_input {
  /**
   * HERDR_INPUT_TEXT_COMMIT, HERDR_INPUT_KEY, or HERDR_INPUT_PASTE.
   */
  uint8_t kind;
  /**
   * NUL-terminated UTF-8 pane id from the latest snapshot; required.
   */
  const char *pane_id;
  /**
   * NUL-terminated UTF-8 text; required for TEXT_COMMIT and PASTE, else null.
   */
  const char *text;
  /**
   * Key payload; read only when `kind == HERDR_INPUT_KEY`.
   */
  struct herdr_key key;
} herdr_input;

/**
 * Rust-owned byte buffer. `data` is null iff `len == 0`; ownership moves to
 * the caller and returns via `herdr_bytes_free` exactly once.
 */
typedef struct herdr_bytes {
  uint8_t *data;
  size_t len;
} herdr_bytes;

/**
 * Creates an endpoint client and queues the generation-1 hello frame; drain
 * it with `herdr_client_drain_outbound`. Returns null on failure with the
 * structured reason in `error_out` (optional).
 */
struct herdr_client *herdr_client_create(const struct herdr_client_config *config,
                                         struct HerdrResult *error_out);

/**
 * Releases the client and every buffer it still owns. The handle must not be
 * used afterwards; byte buffers previously handed out stay caller-owned.
 */
void herdr_client_destroy(struct herdr_client *client);

/**
 * Feeds opaque transport bytes (stdout of the remote bridge) to the decoder.
 */
struct HerdrResult herdr_client_receive(struct herdr_client *client,
                                        const uint8_t *bytes,
                                        size_t len);

/**
 * Sends one semantic input event to an explicit pane target from the latest
 * snapshot. Routing and lease validation happen in the Rust core.
 */
struct HerdrResult herdr_client_send_input(struct herdr_client *client,
                                           const struct herdr_input *input);

/**
 * Pops one complete outbound frame (opaque, length-prefixed) for the
 * transport write; an empty result means the queue is drained.
 */
struct herdr_bytes herdr_client_drain_outbound(struct herdr_client *client,
                                               struct HerdrResult *error_out);

/**
 * Returns the latest accepted shell snapshot as stable JSON
 * (`shell.snapshot.v1` carrier), or empty when none has been accepted.
 */
struct herdr_bytes herdr_client_snapshot(struct herdr_client *client,
                                         struct HerdrResult *error_out);

/**
 * Returns the latest committed pane surface as stable JSON, or empty.
 */
struct herdr_bytes herdr_client_surface(struct herdr_client *client, struct HerdrResult *error_out);

/**
 * HERDR_PHASE_* value of the client.
 */
uint32_t herdr_client_phase(struct herdr_client *client);

/**
 * Bytes buffered awaiting a complete inbound frame (diagnostic bound check).
 */
uint64_t herdr_client_pending_inbound(struct herdr_client *client);

/**
 * Frees a buffer returned by this ABI exactly once; `{null, 0}` is a no-op.
 */
void herdr_bytes_free(struct herdr_bytes bytes);

/**
 * Live allocations currently owned by C callers (diagnostics; zero expected).
 */
uint64_t herdr_debug_live_allocations(void);

/**
 * Library provenance, e.g. "0.9.0" (static, never freed).
 */
const char *herdr_core_version(void);

#endif  /* HERDR_CORE_H */
