import SwiftUI

/// Third-party acknowledgements (integration doc §15: Apache-2.0 and every
/// required third-party license visible in-app). Renders the release-time
/// `THIRD_PARTY_NOTICES.md` generated by cargo-about for the embedded Herdr
/// Rust core, plus the Swift-side dependency inventory pointer.
struct AcknowledgementsView: View {
    @Environment(\.terminalColors) var colors
    @Environment(\.terminalTypography) var typography
    @Environment(\.terminalSpacing) private var spacing

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: spacing.sm) {
                Text("BicTerm embeds the Herdr client core (herdr-protocol, herdr-client-core, herdr-ios-ffi; Apache-2.0) and the third-party components below.")
                    .font(typography.body)
                    .foregroundColor(colors.foreground)
                Text(notices)
                    .font(typography.caption)
                    .foregroundColor(colors.foreground)
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
                Text("Swift-side dependencies (SwiftTerm, swift-nio-ssh and the vendored forks) are inventoried in the repository's DEPENDENCIES.md.")
                    .font(typography.caption)
                    .foregroundColor(colors.dimmed)
            }
            .padding(.vertical, spacing.sm)
        }
        .padding(.horizontal, spacing.sm)
        .scrollContentBackground(.hidden)
        .background(colors.background)
        .navigationTitle("Acknowledgements")
        .accessibilityIdentifier("acknowledgements")
    }

    private var notices: String {
        guard let url = Bundle.main.url(forResource: "THIRD_PARTY_NOTICES", withExtension: "md"),
              let text = try? String(contentsOf: url, encoding: .utf8)
        else {
            return "Third-party notices are unavailable in this build."
        }
        return text
    }
}
